/**
 * Next.js App Router `POST` handler for browser log batches (`@exbrain/common-react` logger shipper).
 * Writes one NDJSON line per entry to stdout for `ob logs` / Promtail / Loki.
 *
 * Uses standard `Request` / `Response` only (no `next` imports) so consuming apps typecheck
 * against their own `next` dependency — avoids duplicate `NextRequest` types when common-react
 * has a nested `node_modules/next`.
 *
 * Import from `@exbrain/common-react/server/client-logs-ingest` (Node route handlers only).
 */

export type ClientLogsIngestOptions = {
  /** Value for the `service` field in each NDJSON line (e.g. `hello-ui`, `exbrain-ui`). */
  service: string;
};

function writeNdjsonLine(obj: Record<string, unknown>): void {
  if (typeof process !== "undefined" && process.stdout?.writable) {
    process.stdout.write(JSON.stringify(obj) + "\n");
  }
}

/**
 * Returns a `POST` function suitable for `app/api/logs/route.ts`.
 * sendBeacon cannot set headers; `browserId` is taken from body or `X-Browser-ID` header.
 * Each log entry's own `requestId` / `request_id` in context is preserved per-entry.
 */
export function createClientLogsPostHandler(options: ClientLogsIngestOptions) {
  const { service } = options;

  return async function POST(request: Request): Promise<Response> {
    try {
      const body = await request.json();
      const browserId =
        (body.browserId as string)?.trim() ||
        request.headers.get("X-Browser-ID")?.trim() ||
        "";
      // Batch request ID: generated by the shipper with `00000000-` prefix to mark it as batch transport.
      // Body is the reliable source (works for both sendBeacon and fetch); fall back to X-Request-ID header.
      const batchRequestId =
        (body.batchRequestId as string)?.trim() ||
        request.headers.get("X-Request-ID")?.trim() ||
        "";
      const logs = Array.isArray(body.logs) ? body.logs : [];
      const url = typeof body.url === "string" ? body.url : "";
      // PII (golden §7): do NOT persist user_agent or client_ip (from x-forwarded-for /
      // x-real-ip). Correlation is via browser_id / request_id only.

      for (const entry of logs) {
        const level = (entry?.level as string) || "info";
        const message = typeof entry?.message === "string" ? entry.message : "—";
        const timestamp = typeof entry?.timestamp === "string" ? entry.timestamp : new Date().toISOString();
        const context =
          typeof entry?.context === "object" && entry.context !== null
            ? (entry.context as Record<string, unknown>)
            : {};
        // Per-entry request_id: prefer entry's own context.requestId, fall back to batch transport X-Request-ID.
        const entryRequestId = (context.requestId as string)?.trim() || (context.request_id as string)?.trim() || batchRequestId;
        // Remove correlation IDs from context spread to avoid duplication
        const { requestId: _r, request_id: _r2, browserId: _b, ...restContext } = context;
        const line: Record<string, unknown> = {
          level,
          message,
          timestamp,
          service,
          browser_id: browserId,
          source: "browser",
          url,
          ...restContext,
        };
        if (entryRequestId) {
          line.request_id = entryRequestId;
        }
        writeNdjsonLine(line);
      }

      return Response.json({ success: true }, { status: 200 });
    } catch {
      return Response.json({ success: false }, { status: 400 });
    }
  };
}
